#!/usr/bin/env python3
"""
plot_seabird_metrics.py

Visualization script for seabird behavior metrics generated by event_detector.py

Usage:
    python3 code/postprocess/plot_seabird_metrics.py results/run1_clean --output plots/
    
This script generates various plots:
- Time series plots for movement and positions
- Bar charts for event summaries and per-minute aggregates
- Scatter plots for flapping events
- Combined overview dashboards
"""


import argparse
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import numpy as np
import os
from datetime import datetime, timedelta
import seaborn as sns

# Set style
plt.style.use('default')
sns.set_palette("husl")

def load_data(prefix):
    """Load all CSV files generated by event_detector.py"""
    data = {}
    
    files = {
        'events': f"{prefix}_events.csv",
        'movement': f"{prefix}_movement.csv", 
        'per_minute': f"{prefix}_per_minute.csv",
        'flaps': f"{prefix}_flaps.csv",
        'per_second': f"{prefix}_per_second.csv"
    }
    
    for key, filename in files.items():
        if os.path.exists(filename):
            data[key] = pd.read_csv(filename)
            print(f"Loaded {filename}: {len(data[key])} rows")
        else:
            print(f"Warning: {filename} not found")
            data[key] = pd.DataFrame()
    
    return data

def seconds_to_time(seconds, start_time="00:00:00"):
    """Convert seconds to time labels for x-axis"""
    start = datetime.strptime(start_time, "%H:%M:%S")
    times = [start + timedelta(seconds=int(s)) for s in seconds]
    return times

def plot_movement_timeseries(movement_df, output_dir, fps=1):
    """Plot movement metrics as time series"""
    if movement_df.empty:
        print("No movement data to plot")
        return
        
    fig, axes = plt.subplots(3, 1, figsize=(15, 10))
    fig.suptitle('Seabird Movement Metrics Over Time', fontsize=16, fontweight='bold')
    
    # Use timestamps if available, otherwise convert seconds to time
    if 'timestamp' in movement_df.columns:
        times = pd.to_datetime(movement_df['timestamp'])
        time_label = 'Time'
    else:
        times = seconds_to_time(movement_df['second'])
        time_label = 'Time (relative)'
    
    # Position over time
    ax1 = axes[0]
    ax1.plot(times, movement_df['x_mean'], 'b-', alpha=0.7, label='X position', linewidth=1)
    ax1.plot(times, movement_df['x_smooth'], 'b-', linewidth=2, label='X smoothed')
    ax1_twin = ax1.twinx()
    ax1_twin.plot(times, movement_df['y_mean'], 'r-', alpha=0.7, label='Y position', linewidth=1)
    ax1_twin.plot(times, movement_df['y_smooth'], 'r-', linewidth=2, label='Y smoothed')
    
    ax1.set_ylabel('X Position (pixels)', color='b')
    ax1_twin.set_ylabel('Y Position (pixels)', color='r')
    ax1.set_title('Adult Seabird Position Over Time')
    ax1.grid(True, alpha=0.3)
    ax1.tick_params(axis='x', rotation=45)
    
    # Add legends
    lines1, labels1 = ax1.get_legend_handles_labels()
    lines2, labels2 = ax1_twin.get_legend_handles_labels()
    ax1.legend(lines1 + lines2, labels1 + labels2, loc='upper right')
    
    # Movement delta over time
    ax2 = axes[1]
    valid_movement = movement_df.dropna(subset=['movement_delta'])
    if not valid_movement.empty:
        if 'timestamp' in movement_df.columns:
            times_valid = pd.to_datetime(valid_movement['timestamp'])
        else:
            times_valid = seconds_to_time(valid_movement['second'])
        ax2.plot(times_valid, valid_movement['movement_delta'], 'g-', linewidth=1, alpha=0.8)
        ax2.fill_between(times_valid, valid_movement['movement_delta'], alpha=0.3, color='green')
    
    ax2.set_ylabel('Movement Delta (pixels)')
    ax2.set_title('Frame-to-Frame Movement Distance')
    ax2.grid(True, alpha=0.3)
    ax2.tick_params(axis='x', rotation=45)
    
    # Movement histogram
    ax3 = axes[2]
    if not valid_movement.empty:
        ax3.hist(valid_movement['movement_delta'], bins=30, alpha=0.7, color='green', edgecolor='black')
        ax3.axvline(valid_movement['movement_delta'].mean(), color='red', linestyle='--', 
                   label=f'Mean: {valid_movement["movement_delta"].mean():.1f} px')
        ax3.axvline(valid_movement['movement_delta'].median(), color='orange', linestyle='--',
                   label=f'Median: {valid_movement["movement_delta"].median():.1f} px')
    
    ax3.set_xlabel('Movement Delta (pixels)')
    ax3.set_ylabel('Frequency')
    ax3.set_title('Distribution of Movement Distances')
    ax3.legend()
    ax3.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'movement_timeseries.png'), dpi=300, bbox_inches='tight')
    plt.show()

def plot_events_timeline(events_df, output_dir):
    """Plot arrival/departure events as timeline"""
    if events_df.empty:
        print("No events data to plot")
        return
        
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(15, 8))
    fig.suptitle('Seabird Arrival and Departure Events', fontsize=16, fontweight='bold')
    
    # Timeline plot
    arrivals = events_df[events_df['type'] == 'arrival']
    departures = events_df[events_df['type'] == 'departure']
    
    if not arrivals.empty:
        if 'timestamp' in arrivals.columns:
            arrival_times = pd.to_datetime(arrivals['timestamp'])
        else:
            arrival_times = seconds_to_time(arrivals['second'])
        ax1.scatter(arrival_times, [1]*len(arrival_times), c='green', s=100, 
                   alpha=0.7, label=f'Arrivals ({len(arrivals)})', marker='^')
    
    if not departures.empty:
        if 'timestamp' in departures.columns:
            departure_times = pd.to_datetime(departures['timestamp'])
        else:
            departure_times = seconds_to_time(departures['second'])
        ax1.scatter(departure_times, [0.5]*len(departure_times), c='red', s=100,
                   alpha=0.7, label=f'Departures ({len(departures)})', marker='v')
    
    # Add arrivals with fish
    arrivals_with_fish = arrivals[arrivals['arrival_with_fish'] == True]
    if not arrivals_with_fish.empty:
        if 'timestamp' in arrivals_with_fish.columns:
            fish_times = pd.to_datetime(arrivals_with_fish['timestamp'])
        else:
            fish_times = seconds_to_time(arrivals_with_fish['second'])
        ax1.scatter(fish_times, [1.2]*len(fish_times), c='blue', s=150,
                   alpha=0.8, label=f'Arrivals with Fish ({len(arrivals_with_fish)})', marker='*')
    
    ax1.set_ylabel('Event Type')
    ax1.set_title('Event Timeline')
    ax1.set_ylim(0, 1.5)
    ax1.set_yticks([0.5, 1, 1.2])
    ax1.set_yticklabels(['Departure', 'Arrival', 'Arrival + Fish'])
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    ax1.tick_params(axis='x', rotation=45)
    
    # Event counts per hour
    if not events_df.empty:
        events_df['hour'] = events_df['second'] // 3600
        hourly_counts = events_df.groupby(['hour', 'type']).size().unstack(fill_value=0)
        
        hours = hourly_counts.index
        width = 0.35
        
        if 'arrival' in hourly_counts.columns:
            ax2.bar(hours - width/2, hourly_counts['arrival'], width, 
                   label='Arrivals', alpha=0.8, color='green')
        
        if 'departure' in hourly_counts.columns:
            ax2.bar(hours + width/2, hourly_counts['departure'], width,
                   label='Departures', alpha=0.8, color='red')
        
        ax2.set_xlabel('Hour')
        ax2.set_ylabel('Event Count')
        ax2.set_title('Events Per Hour')
        ax2.legend()
        ax2.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'events_timeline.png'), dpi=300, bbox_inches='tight')
    plt.show()

def plot_flapping_events(flaps_df, output_dir):
    """Plot flapping detection events"""
    if flaps_df.empty:
        print("No flapping data to plot")
        return
        
    fig, axes = plt.subplots(2, 2, figsize=(15, 10))
    fig.suptitle('Wing Flapping Detection Results', fontsize=16, fontweight='bold')
    
    # Timeline of flapping events
    ax1 = axes[0, 0]
    if 'timestamp' in flaps_df.columns:
        times = pd.to_datetime(flaps_df['timestamp'])
    else:
        times = seconds_to_time(flaps_df['second'])
    scatter = ax1.scatter(times, flaps_df['multiplier'], c=flaps_df['area'], 
                         s=80, alpha=0.7, cmap='viridis')
    ax1.set_ylabel('Area Multiplier')
    ax1.set_title('Flapping Events Over Time')
    ax1.tick_params(axis='x', rotation=45)
    ax1.grid(True, alpha=0.3)
    plt.colorbar(scatter, ax=ax1, label='Bbox Area (px²)')
    
    # Spatial distribution of flapping
    ax2 = axes[0, 1]
    scatter2 = ax2.scatter(flaps_df['center_x'], flaps_df['center_y'], 
                          c=flaps_df['multiplier'], s=flaps_df['area']/1000,
                          alpha=0.7, cmap='plasma')
    ax2.set_xlabel('X Position (pixels)')
    ax2.set_ylabel('Y Position (pixels)')
    ax2.set_title('Spatial Distribution of Flapping')
    ax2.grid(True, alpha=0.3)
    plt.colorbar(scatter2, ax=ax2, label='Area Multiplier')
    
    # Area multiplier distribution
    ax3 = axes[1, 0]
    ax3.hist(flaps_df['multiplier'], bins=20, alpha=0.7, color='orange', edgecolor='black')
    ax3.axvline(flaps_df['multiplier'].mean(), color='red', linestyle='--',
               label=f'Mean: {flaps_df["multiplier"].mean():.1f}')
    ax3.set_xlabel('Area Multiplier')
    ax3.set_ylabel('Frequency')
    ax3.set_title('Distribution of Area Multipliers')
    ax3.legend()
    ax3.grid(True, alpha=0.3)
    
    # Confidence vs multiplier
    ax4 = axes[1, 1]
    ax4.scatter(flaps_df['confidence'], flaps_df['multiplier'], alpha=0.7, color='purple')
    ax4.set_xlabel('Detection Confidence')
    ax4.set_ylabel('Area Multiplier')
    ax4.set_title('Confidence vs Area Multiplier')
    ax4.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'flapping_analysis.png'), dpi=300, bbox_inches='tight')
    plt.show()

def plot_per_minute_summary(per_minute_df, output_dir):
    """Plot per-minute aggregated metrics"""
    if per_minute_df.empty:
        print("No per-minute data to plot")
        return
        
    fig, axes = plt.subplots(2, 2, figsize=(15, 10))
    fig.suptitle('Per-Minute Activity Summary', fontsize=16, fontweight='bold')
    
    minutes = per_minute_df['minute']
    
    # Adult count over time
    ax1 = axes[0, 0]
    ax1.plot(minutes, per_minute_df['total_adult_count'], 'b-', linewidth=2, marker='o', markersize=4)
    ax1.fill_between(minutes, per_minute_df['total_adult_count'], alpha=0.3, color='blue')
    ax1.set_xlabel('Minute')
    ax1.set_ylabel('Total Adult Count')
    ax1.set_title('Adult Activity Per Minute')
    ax1.grid(True, alpha=0.3)
    
    # Events per minute
    ax2 = axes[0, 1]
    width = 0.35
    ax2.bar(minutes - width/2, per_minute_df['arrivals'], width, 
           label='Arrivals', alpha=0.8, color='green')
    ax2.bar(minutes + width/2, per_minute_df['departures'], width,
           label='Departures', alpha=0.8, color='red')
    ax2.set_xlabel('Minute')
    ax2.set_ylabel('Event Count')
    ax2.set_title('Arrivals vs Departures Per Minute')
    ax2.legend()
    ax2.grid(True, alpha=0.3)
    
    # Movement and flapping
    ax3 = axes[1, 0]
    valid_movement = per_minute_df[per_minute_df['avg_movement_delta_px'] > 0]
    if not valid_movement.empty:
        ax3.bar(valid_movement['minute'], valid_movement['avg_movement_delta_px'], 
               alpha=0.7, color='orange', label='Avg Movement')
    ax3.set_xlabel('Minute')
    ax3.set_ylabel('Average Movement (pixels)')
    ax3.set_title('Average Movement Per Minute')
    ax3.grid(True, alpha=0.3)
    
    # Activity heatmap (summary statistics)
    ax4 = axes[1, 1]
    # Create activity score combining arrivals, departures, and adult presence
    activity_score = (per_minute_df['arrivals'] + per_minute_df['departures'] + 
                     per_minute_df['total_adult_count']/10 + per_minute_df['flapping_events'])
    
    bars = ax4.bar(minutes, activity_score, alpha=0.7, color='purple')
    ax4.set_xlabel('Minute')
    ax4.set_ylabel('Activity Score')
    ax4.set_title('Combined Activity Score Per Minute')
    ax4.grid(True, alpha=0.3)
    
    # Color bars by intensity
    max_score = activity_score.max() if len(activity_score) > 0 else 1
    for bar, score in zip(bars, activity_score):
        intensity = score / max_score if max_score > 0 else 0
        bar.set_color(plt.cm.viridis(intensity))
    
    plt.tight_layout()
    plt.savefig(os.path.join(output_dir, 'per_minute_summary.png'), dpi=300, bbox_inches='tight')
    plt.show()

def plot_overview_dashboard(data, output_dir):
    """Create comprehensive overview dashboard"""
    fig = plt.figure(figsize=(20, 12))
    fig.suptitle('Seabird Behavior Analysis Dashboard', fontsize=20, fontweight='bold')
    
    # Create grid layout
    gs = fig.add_gridspec(3, 4, hspace=0.3, wspace=0.3)
    
    # Summary statistics (top left)
    ax1 = fig.add_subplot(gs[0, 0])
    
    stats_text = []
    if not data['events'].empty:
        n_arrivals = len(data['events'][data['events']['type'] == 'arrival'])
        n_departures = len(data['events'][data['events']['type'] == 'departure'])
        n_fish_arrivals = len(data['events'][(data['events']['type'] == 'arrival') & 
                                           (data['events']['arrival_with_fish'] == True)])
        stats_text.extend([
            f"Total Arrivals: {n_arrivals}",
            f"Total Departures: {n_departures}",
            f"Arrivals with Fish: {n_fish_arrivals}"
        ])
    
    if not data['flaps'].empty:
        stats_text.append(f"Flapping Events: {len(data['flaps'])}")
    
    if not data['movement'].empty:
        avg_movement = data['movement']['movement_delta'].mean()
        stats_text.append(f"Avg Movement: {avg_movement:.1f} px")
    
    if not data['per_minute'].empty:
        total_minutes = len(data['per_minute'])
        avg_adults = data['per_minute']['mean_adult_count_per_s'].mean()
        stats_text.extend([
            f"Duration: {total_minutes} minutes",
            f"Avg Adults/sec: {avg_adults:.2f}"
        ])
    
    ax1.text(0.1, 0.9, '\n'.join(stats_text), transform=ax1.transAxes, fontsize=12,
             verticalalignment='top', bbox=dict(boxstyle='round', facecolor='lightblue', alpha=0.8))
    ax1.set_xlim(0, 1)
    ax1.set_ylim(0, 1)
    ax1.axis('off')
    ax1.set_title('Summary Statistics', fontweight='bold')
    
    # Event timeline with adult count background (top middle - wider)
    ax2 = fig.add_subplot(gs[0, 1:])
    
    # First plot the raw adult count as background context
    if not data['per_second'].empty:
        if 'timestamp' in data['per_second'].columns:
            time_data = pd.to_datetime(data['per_second']['timestamp'])
            time_label = 'Time'
            # Format x-axis for better readability
            ax2.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M:%S'))
            ax2.xaxis.set_major_locator(mdates.MinuteLocator(interval=2))
        else:
            time_data = data['per_second']['second'] / 60  # convert to minutes
            time_label = 'Time (minutes)'
        
        # Plot adult count as line with secondary y-axis
        ax2_twin = ax2.twinx()
        ax2_twin.plot(time_data, data['per_second']['count_adult'], 'lightblue', 
                     linewidth=1, alpha=0.7, label='Adult Count')
        ax2_twin.set_ylabel('Adult Count', color='lightblue')
        ax2_twin.tick_params(axis='y', labelcolor='lightblue')
    
    # Overlay arrival/departure events
    if not data['events'].empty:
        arrivals = data['events'][data['events']['type'] == 'arrival']
        departures = data['events'][data['events']['type'] == 'departure']
        
        if not arrivals.empty:
            if 'timestamp' in arrivals.columns:
                arrival_times = pd.to_datetime(arrivals['timestamp'])
            else:
                arrival_times = arrivals['second'] / 60
            ax2.scatter(arrival_times, [1]*len(arrivals), c='green', s=80, 
                       alpha=0.9, label='Arrivals', marker='^', zorder=5)
        
        if not departures.empty:
            if 'timestamp' in departures.columns:
                departure_times = pd.to_datetime(departures['timestamp'])
            else:
                departure_times = departures['second'] / 60
            ax2.scatter(departure_times, [0.5]*len(departures), c='red', s=80,
                       alpha=0.9, label='Departures', marker='v', zorder=5)
    
    ax2.set_ylabel('Event Type')
    ax2.set_xlabel(time_label if 'time_label' in locals() else 'Time')
    ax2.set_title('Event Timeline with Adult Count Context')
    ax2.set_ylim(0, 1.5)
    ax2.set_yticks([0.5, 1])
    ax2.set_yticklabels(['Departure', 'Arrival'])
    
    # Combine legends from both y-axes
    lines1, labels1 = ax2.get_legend_handles_labels()
    if 'ax2_twin' in locals():
        lines2, labels2 = ax2_twin.get_legend_handles_labels()
        ax2.legend(lines1 + lines2, labels1 + labels2, loc='upper right')
    else:
        ax2.legend()
    
    ax2.grid(True, alpha=0.3)
    if 'timestamp' in (data['per_second'].columns if not data['per_second'].empty else []):
        ax2.tick_params(axis='x', rotation=45)
    
    # Movement over time (middle row)
    ax4 = fig.add_subplot(gs[1, :2])
    if not data['movement'].empty:
        if 'timestamp' in data['movement'].columns:
            movement_times = pd.to_datetime(data['movement']['timestamp'])
            ax4.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M:%S'))
            ax4.xaxis.set_major_locator(mdates.MinuteLocator(interval=2))
            time_label = 'Time'
        else:
            movement_times = data['movement']['second'] / 60
            time_label = 'Time (minutes)'
            
        ax4.plot(movement_times, data['movement']['x_smooth'], 'b-', 
                linewidth=1, label='X position', alpha=0.8)
        ax4_twin = ax4.twinx()
        ax4_twin.plot(movement_times, data['movement']['y_smooth'], 'r-',
                     linewidth=1, label='Y position', alpha=0.8)
        ax4.set_xlabel(time_label)
        ax4.set_ylabel('X Position', color='b')
        ax4_twin.set_ylabel('Y Position', color='r')
        ax4.set_title('Position Over Time')
        if 'timestamp' in data['movement'].columns:
            ax4.tick_params(axis='x', rotation=45)
        ax4.grid(True, alpha=0.3)
    
    # Flapping spatial distribution (middle right)
    ax5 = fig.add_subplot(gs[1, 2:])
    if not data['flaps'].empty:
        scatter = ax5.scatter(data['flaps']['center_x'], data['flaps']['center_y'],
                            c=data['flaps']['multiplier'], s=60, alpha=0.7, cmap='plasma')
        ax5.set_xlabel('X Position')
        ax5.set_ylabel('Y Position')
        ax5.set_title('Flapping Locations')
        plt.colorbar(scatter, ax=ax5, label='Multiplier')
    
    # Per-minute activity pattern (bottom left)
    ax6 = fig.add_subplot(gs[2, :2])
    if not data['per_minute'].empty:
        # Use actual timestamps if available for minute labels
        if 'timestamp' in data['per_second'].columns and not data['per_second'].empty:
            # Get start time for minute calculation
            start_time = pd.to_datetime(data['per_second']['timestamp'].iloc[0])
            minute_labels = [(start_time + pd.Timedelta(minutes=int(m))).strftime('%H:%M') 
                           for m in data['per_minute']['minute']]
            x_pos = range(len(data['per_minute']))
        else:
            minute_labels = data['per_minute']['minute']
            x_pos = minute_labels
        
        width = 0.2
        ax6.bar([x - 1.5*width for x in x_pos], data['per_minute']['arrivals'], width, 
               label='Arrivals', alpha=0.8)
        ax6.bar([x - 0.5*width for x in x_pos], data['per_minute']['departures'], width, 
               label='Departures', alpha=0.8)
        ax6.bar([x + 0.5*width for x in x_pos], data['per_minute']['total_adult_count']/10, width, 
               label='Adults/10', alpha=0.8)
        ax6.bar([x + 1.5*width for x in x_pos], data['per_minute']['flapping_events'], width, 
               label='Flaps', alpha=0.8)
        
        if 'timestamp' in data['per_second'].columns and not data['per_second'].empty:
            ax6.set_xlabel('Time')
            ax6.set_xticks(x_pos)
            ax6.set_xticklabels(minute_labels, rotation=45)
        else:
            ax6.set_xlabel('Minute')
        ax6.set_ylabel('Count')
        ax6.set_title('Per-Minute Activity Pattern')
        ax6.legend()
        ax6.grid(True, alpha=0.3)
    
    # Movement distribution (bottom right)
    ax7 = fig.add_subplot(gs[2, 2:])
    if not data['movement'].empty:
        valid_movement = data['movement'].dropna(subset=['movement_delta'])
        if not valid_movement.empty:
            ax7.hist(valid_movement['movement_delta'], bins=20, alpha=0.7, 
                    color='green', edgecolor='black')
            ax7.axvline(valid_movement['movement_delta'].mean(), color='red', 
                       linestyle='--', label=f'Mean: {valid_movement["movement_delta"].mean():.1f}')
            ax7.set_xlabel('Movement (pixels)')
            ax7.set_ylabel('Frequency')
            ax7.set_title('Movement Distribution')
            ax7.legend()
            ax7.grid(True, alpha=0.3)
    
    plt.savefig(os.path.join(output_dir, 'overview_dashboard.png'), dpi=300, bbox_inches='tight')
    plt.show()

def generate_summary_report(data, output_dir):
    """Generate text summary report"""
    report_path = os.path.join(output_dir, 'analysis_summary.txt')
    
    with open(report_path, 'w') as f:
        f.write("SEABIRD BEHAVIOR ANALYSIS SUMMARY\n")
        f.write("=" * 50 + "\n\n")
        
        # Add timestamp information if available
        if not data['per_second'].empty and 'timestamp' in data['per_second'].columns:
            start_time = pd.to_datetime(data['per_second']['timestamp'].iloc[0])
            end_time = pd.to_datetime(data['per_second']['timestamp'].iloc[-1])
            f.write("OBSERVATION PERIOD:\n")
            f.write(f"  Start Time: {start_time.strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"  End Time: {end_time.strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"  Duration: {(end_time - start_time).total_seconds():.0f} seconds ({(end_time - start_time).total_seconds()/60:.1f} minutes)\n\n")
        
        # Events summary
        if not data['events'].empty:
            events = data['events']
            arrivals = events[events['type'] == 'arrival']
            departures = events[events['type'] == 'departure']
            fish_arrivals = arrivals[arrivals['arrival_with_fish'] == True]
            
            f.write("EVENT SUMMARY:\n")
            f.write(f"  Total Arrivals: {len(arrivals)}\n")
            f.write(f"  Total Departures: {len(departures)}\n")
            f.write(f"  Arrivals with Fish: {len(fish_arrivals)} ({len(fish_arrivals)/len(arrivals)*100 if len(arrivals) > 0 else 0:.1f}%)\n")
            
            # Add actual timestamps for events if available
            if 'timestamp' in events.columns:
                f.write("  Event Times:\n")
                for _, event in events.iterrows():
                    timestamp = pd.to_datetime(event['timestamp']).strftime('%H:%M:%S')
                    f.write(f"    {event['type'].title()} at {timestamp}\n")
            
            f.write(f"  Average time between events: {events['second'].diff().mean():.1f} seconds\n\n")
        
        # Movement summary
        if not data['movement'].empty:
            movement = data['movement'].dropna(subset=['movement_delta'])
            if not movement.empty:
                f.write("MOVEMENT SUMMARY:\n")
                f.write(f"  Average movement per frame: {movement['movement_delta'].mean():.1f} pixels\n")
                f.write(f"  Maximum movement: {movement['movement_delta'].max():.1f} pixels\n")
                f.write(f"  Total frames with movement: {len(movement)}\n\n")
        
        # Flapping summary
        if not data['flaps'].empty:
            flaps = data['flaps']
            f.write("FLAPPING SUMMARY:\n")
            f.write(f"  Total flapping events: {len(flaps)}\n")
            f.write(f"  Average area multiplier: {flaps['multiplier'].mean():.2f}\n")
            f.write(f"  Maximum area multiplier: {flaps['multiplier'].max():.2f}\n\n")
        
        # Per-minute summary
        if not data['per_minute'].empty:
            per_min = data['per_minute']
            f.write("ACTIVITY SUMMARY:\n")
            f.write(f"  Total observation time: {len(per_min)} minutes\n")
            f.write(f"  Average adults per minute: {per_min['total_adult_count'].mean():.1f}\n")
            f.write(f"  Most active minute: {per_min['total_adult_count'].idxmax()} (minute {per_min.loc[per_min['total_adult_count'].idxmax(), 'minute']})\n")
            f.write(f"  Peak adult count: {per_min['total_adult_count'].max()}\n")
    
    print(f"Summary report saved to {report_path}")

def main():
    parser = argparse.ArgumentParser(description='Plot seabird behavior metrics')
    parser.add_argument('prefix', help='File prefix (e.g., results/run1_clean)')
    parser.add_argument('--output', '-o', default='plots/', help='Output directory for plots')
    parser.add_argument('--fps', type=int, default=1, help='Frames per second (for time conversion)')
    parser.add_argument('--start_time', default='00:00:00', help='Start time for x-axis labels (HH:MM:SS)')
    
    args = parser.parse_args()
    
    # Create output directory
    os.makedirs(args.output, exist_ok=True)
    
    # Load data
    print(f"Loading data from {args.prefix}...")
    data = load_data(args.prefix)
    
    # Generate plots
    print("Generating plots...")
    
    plot_movement_timeseries(data['movement'], args.output, args.fps)
    plot_events_timeline(data['events'], args.output)
    plot_flapping_events(data['flaps'], args.output)
    plot_per_minute_summary(data['per_minute'], args.output)
    plot_overview_dashboard(data, args.output)
    
    # Generate summary report
    generate_summary_report(data, args.output)
    
    print(f"All plots saved to {args.output}")
    print("Analysis complete!")

if __name__ == "__main__":
    main()